### ISSUE TITLE
wfs layers don't toggle off

### ISSUE THREAD

**Issue by josephmsms** [ggcity/map-viewer#5]
I rearranged the groupings and the wfs is stuck on again

**Comment by mooman** [comment]
Can you include your config file please

**Comment by josephmsms** [comment]
moved it down and it works again

**Comment by josephmsms** [comment]
initialCenter:
  - 33.769
  - -117.9955
initialZoom: 13
maxZoom: 13
minZoom: 13

baseMaps:
  - source: '//www.ci.garden-grove.ca.us/tileserver/styles/gg-basic/{z}/{x}/{y}.png'
    format: XYZ
    attribution: '&copy; OpenStreetMap'
  - source: //www.ci.garden-grove.ca.us/geoserver/gwc/service/wms
    format: WMS
    layers: 'gis:2017_aerials'

wmsDefaultSource: //www.ci.garden-grove.ca.us/geoserver/gis/wms

overlayMaps:
  - machineName: planning
    name: Planning
    description: 'Code Enforcement, CDBG, Redevelopment, etc'
    layers:
      alwaysOn:
        - machineName: 'gis:city_boundary'
      exclusives:
        - machineName: 'gis:city_owned_parcels'
          name: City Owned Parcels
          visible: true
        - machineName: 'gis:redev'
          name: Redevelopment Zones
        - machineName: 'gis:cdbg'
          name: CDBG

        - machineName: 'gis:building_open_permits'
          source: //www.ci.garden-grove.ca.us/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:building_open_permits&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Open Building Permits
          type: geojson
          radius: 4
          weight: 1
          maxClusterRadius: 120
          identify: true
          cluster: true
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true

  - machineName: code-enforcement
    name: Code Enforcement
    description: 'Code Enforcement'
    layers:
      alwaysOn:
        - machineName: 'gis:city_boundary'
      exclusives:
        - machineName: 'gis:code_enforcement_violations'
          source: //www.ci.garden-grove.ca.us/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:code_enforcement_violations&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Code Enforcement Violations
          type: geojson
          radius: 4
          weight: 1
          maxClusterRadius: 120
          identify: true
          cluster: true
          visible: true
        - machineName: 'gis:code_enf_officer_coverage'
          name: Code Enforcement Coverage
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true

**Comment by josephmsms** [comment]
`baseMaps:
  - source: '//www.ci.garden-grove.ca.us/tileserver/styles/gg-basic/{z}/{x}/{y}.png'
    format: XYZ
    attribution: '&copy; OpenStreetMap'
  - source: //www.ci.garden-grove.ca.us/geoserver/gwc/service/wms
    format: WMS
    layers: 'gis:2017_aerials'

wmsDefaultSource: //www.ci.garden-grove.ca.us/geoserver/gis/wms

overlayMaps:
  - machineName: planning
    name: Planning
    description: 'Code Enforcement, CDBG, Redevelopment, etc'
    layers:
      alwaysOn:
        - machineName: 'gis:city_boundary'
      exclusives:
        - machineName: 'gis:city_owned_parcels'
          name: City Owned Parcels
          visible: true
        - machineName: 'gis:redev'
          name: Redevelopment Zones
        - machineName: 'gis:cdbg'
          name: CDBG

        - machineName: 'gis:building_open_permits'
          source: //www.ci.garden-grove.ca.us/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:building_open_permits&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Open Building Permits
          type: geojson
          radius: 4
          weight: 1
          maxClusterRadius: 120
          identify: true
          cluster: true
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true

  - machineName: code-enforcement
    name: Code Enforcement
    description: 'Code Enforcement'
    layers:
      alwaysOn:
        - machineName: 'gis:city_boundary'
      exclusives:
        - machineName: 'gis:code_enforcement_violations'
          source: //www.ci.garden-grove.ca.us/geoserver/gis/ows?service=WFS&version=1.0.0&request=GetFeature&typeName=gis:code_enforcement_violations&outputFormat=application%2Fjson&srsName=EPSG:4326
          name: Code Enforcement Violations
          type: geojson
          radius: 4
          weight: 1
          maxClusterRadius: 120
          identify: true
          cluster: true
          visible: true
        - machineName: 'gis:code_enf_officer_coverage'
          name: Code Enforcement Coverage
    initialCenter:
      - 33.769
      - -117.9955
    initialZoom: 13
    resetViewOnSelect: true
`

**Comment by mooman** [comment]
Add the file as attachment please. And is this the broken config?
